<?php
  use CRM_Groupsyncwithrole_ExtensionUtil as E;
  return [
    'select_group_1' => [
      'name' => 'select_group_1',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select Group 1 CiviCRM'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select group 1 CiviCRM'),
      'options' => CRM_Groupsyncwithrole_Utils::getGroupsCiviCRM(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],
    'select_rolecms_1' => [
      'name' => 'select_rolecms_1',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select WordPress role 1'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select WordPress role 1'),
      'options' => CRM_Groupsyncwithrole_Utils::getRoleCMSWP(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],

    'select_group_2' => [
      'name' => 'select_group_2',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select Group 2 CiviCRM'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select group 2 CiviCRM'),
      'options' => CRM_Groupsyncwithrole_Utils::getGroupsCiviCRM(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],
    'select_rolecms_2' => [
      'name' => 'select_rolecms_2',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select WordPress role 2'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select WordPress role 2'),
      'options' => CRM_Groupsyncwithrole_Utils::getRoleCMSWP(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],

    'select_group_3' => [
      'name' => 'select_group_3',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select Group 3 CiviCRM'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select group 3 CiviCRM'),
      'options' => CRM_Groupsyncwithrole_Utils::getGroupsCiviCRM(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],
    'select_rolecms_3' => [
      'name' => 'select_rolecms_3',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select WordPress role 3'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select WordPress role 3'),
      'options' => CRM_Groupsyncwithrole_Utils::getRoleCMSWP(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],

    'select_group_4' => [
      'name' => 'select_group_4',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select Group 4 CiviCRM'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select group 4 CiviCRM'),
      'options' => CRM_Groupsyncwithrole_Utils::getGroupsCiviCRM(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],
    'select_rolecms_4' => [
      'name' => 'select_rolecms_4',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select WordPress role 4'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select WordPress role 4'),
      'options' => CRM_Groupsyncwithrole_Utils::getRoleCMSWP(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],

    'select_group_5' => [
      'name' => 'select_group_5',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select Group 5 CiviCRM'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select group 5 CiviCRM'),
      'options' => CRM_Groupsyncwithrole_Utils::getGroupsCiviCRM(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],
    'select_rolecms_5' => [
      'name' => 'select_rolecms_5',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select WordPress role 5'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select WordPress role 5'),
      'options' => CRM_Groupsyncwithrole_Utils::getRoleCMSWP(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],

    'select_group_6' => [
      'name' => 'select_group_6',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select Group 6 CiviCRM'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select group 6 CiviCRM'),
      'options' => CRM_Groupsyncwithrole_Utils::getGroupsCiviCRM(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],
    'select_rolecms_6' => [
      'name' => 'select_rolecms_6',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select WordPress role 6'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select WordPress role 6'),
      'options' => CRM_Groupsyncwithrole_Utils::getRoleCMSWP(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],

    'select_group_7' => [
      'name' => 'select_group_7',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select Group 7 CiviCRM'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select group 7 CiviCRM'),
      'options' => CRM_Groupsyncwithrole_Utils::getGroupsCiviCRM(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],
    'select_rolecms_7' => [
      'name' => 'select_rolecms_7',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select WordPress role 7'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select WordPress role 7'),
      'options' => CRM_Groupsyncwithrole_Utils::getRoleCMSWP(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],

    'select_group_8' => [
      'name' => 'select_group_8',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select Group 8 CiviCRM'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select group 8 CiviCRM'),
      'options' => CRM_Groupsyncwithrole_Utils::getGroupsCiviCRM(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],
    'select_rolecms_8' => [
      'name' => 'select_rolecms_8',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select WordPress role 8'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select WordPress role 8'),
      'options' => CRM_Groupsyncwithrole_Utils::getRoleCMSWP(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],

    'select_group_9' => [
      'name' => 'select_group_9',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select Group 9 CiviCRM'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select group 9 CiviCRM'),
      'options' => CRM_Groupsyncwithrole_Utils::getGroupsCiviCRM(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],
    'select_rolecms_9' => [
      'name' => 'select_rolecms_9',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select WordPress role 9'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select WordPress role 9'),
      'options' => CRM_Groupsyncwithrole_Utils::getRoleCMSWP(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],

    'select_group_10' => [
      'name' => 'select_group_10',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select Group 10 CiviCRM'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select group 10 CiviCRM'),
      'options' => CRM_Groupsyncwithrole_Utils::getGroupsCiviCRM(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],
    'select_rolecms_10' => [
      'name' => 'select_rolecms_10',
      'type' => 'String',
      'default' => NULL,
      'html_type' => 'select',
      'add' => '4.7',
      'title' => E::ts('Select WordPress role 10'),
      'is_domain' => 1,
      'is_contact' => 0,
      'description' => E::ts('Select WordPress role 10'),
      'options' => CRM_Groupsyncwithrole_Utils::getRoleCMSWP(),
      'settings_pages' => ['groupsyncwithrole' => ['weight' => 150]],
    ],
  ];